# Generated by Django 3.1.7 on 2021-03-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210322_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='registation',
            name='username',
        ),
        migrations.AddField(
            model_name='registation',
            name='name',
            field=models.CharField(default=5, max_length=10),
            preserve_default=False,
        ),
    ]
