# Generated by Django 3.1.7 on 2021-03-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210323_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
