# Generated by Django 3.1.7 on 2021-03-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_cat', models.CharField(max_length=20)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_price', models.PositiveIntegerField()),
                ('p_img', models.ImageField(upload_to='')),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sub_category')),
            ],
        ),
    ]
