# Generated by Django 3.1.7 on 2021-03-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_cat',
        ),
    ]
