# Generated by Django 3.1.7 on 2021-04-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_category',
        ),
    ]
