# Generated by Django 3.1.7 on 2021-04-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='p_price',
        ),
    ]
