# Generated by Django 3.1.7 on 2021-04-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
