# Generated by Django 3.1.7 on 2021-04-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210415_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_dis',
            field=models.TextField(null=True),
        ),
    ]
