# Generated by Django 3.1.7 on 2021-04-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_p_dis'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
