# Generated by Django 3.1.7 on 2021-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210427_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Pending', max_length=100, verbose_name=(('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packing', 'Packing'), ('Delivery', 'Delivery'))),
        ),
    ]
