# Generated by Django 3.1.7 on 2021-05-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packing', 'Packing'), ('Delivery', 'Delivery')], default='Pending', max_length=100),
        ),
    ]
